
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kotlin_jwt_auth}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:developer}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rahasia}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.application.name=api.kotlin
server.port=8081
#server.error.include-stacktrace=always


# JWT config
template_api.jwt.secret=${JWT_SECRET:4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c}
template_api.jwt.expiration=${JWT_EXPIRATION:9000000000}
template_api.jwt.issuer=${JWT_ISSUER:template api}

# super admin config
template_api.super-admin.email=${SUPER_ADMIN_EMAIL:tami@ganteng.com}
template_api.super-admin.username=${SUPER_ADMIN_USERNAME:admin123}
template_api.super-admin.password=${SUPER_ADMIN_PASSWORD:12345678}

# hash salt
hashed.salt=secrethahahahah

template_api.url-frontend=${URL_FRONTEND:http://localhost:4200}

# Swagger Path
springdoc.api-docs.path=/api-docs

#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.boot=TRACE
# application.properties
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.type.descriptor.sql=trace


# gmail smtp
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# image upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.h2.console.enabled=true
template_api.image.path=${IMAGE_PATH:storage/uploads/}

midtrans.api.key=${MIDTRANS_API_KEY}
midtrans.snap.url=${MIDTRANS_SNAP_URL:https://app.sandbox.midtrans.com/snap/v1/transactions}

# oauth2
spring.security.oauth2.client.registration.google.client-id=${YOUR_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${YOUR_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.redirect.url=${YOUR_REDIRECT_URL:http://localhost:4200/guest/login}
spring.security.oauth2.grant.type=authorization_code
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo








